config/routes.rb
Rails.application.routes.draw do
  
  ####################################################
  ############### APPLICATION ROUTES #################
  ####################################################
  # Root route (Home page)
  root to: 'pages#home'

   # Blogs routes
  resources :blogs do 
    member do 
       get :toggle_status 
    end
  end

  # static pages routes
  # get 'about', to: 'pages#about'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  # Portfolio routes
  # customize resource specific route
  resources :portfolios , except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  # get 'portfolio/:id/edit', to: 'portfolios#edit', as: 'portfolio_edit'




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

# Create enum to toggle post status
  enum status: { draft: 0, published: 1 }

# Friendly id gem implemintation
  extend FriendlyId
  friendly_id :title, use: :slugged

# Validations
  validates_presence_of :title, :body

  # Relation ships
  belongs_to :topic

end

app/models/concerns/placeholder.rb
=begin
	This concern wiil be shared in the models
=end
module Placeholder
  extend ActiveSupport::Concern
  def self.image_generator(height:, width:)
  	"http://placehold.it/#{height}x#{width}"
  end

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
# Relationship with technology
  has_many :technologies

=begin
  Add nested attributes(technplogies) to Portfolio model
=end
# Nested attributes with validations for name
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda {|attrs| attrs['name'].blank?}

#  invoke the concern
	include Placeholder

  
  ##### Valodation
  validates_presence_of :title, :body, :main_image, :thumb_image

  ##### Create scopes
  # method 01 :: using class method
  def self.angular 
  	where(subtitle: "Angular")
  end	

  # method 02 :: using scope keyword with lambdas
  scope :ruby_on_rails_items, -> {where(subtitle: "Ruby on rails")} 

  ##### Create default value using rails callbacks
  after_initialize :set_defaults
  # use Placeholder concern
  def set_defaults
  	self.main_image ||= Placeholder.image_generator(height:600, width:400)
  	self.thumb_image ||= Placeholder.image_generator(height:350, width:200)
  end

end

app/models/skill.rb
class Skill < ApplicationRecord
#  invoke the concern
include Placeholder

#####  validations
  validates_presence_of :title, :percent_utilized

 ##### Create default value using rails callbacks
  after_initialize :set_defaults
  # use Placeholder concern
  def set_defaults
  	self.badge ||= Placeholder.image_generator(height:250, width:250)
  end
  

end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
# Validations
	validates_presence_of :title
 
 # Relation ships
	has_many :blogs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  # GET /blogs
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
    end
  end

  # Toggle status action
  def toggle_status 

    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end 
    redirect_to blogs_url, notice: 'status updtaed'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  ########## ALL PORTFOLIOS ##########
  def index
    @portfolio_items = Portfolio.all
    # using ruby_on_rails_items scope
    # @portfolio_items = Portfolio.ruby_on_rails_items
    # using angular scope
    # @portfolio_items = Portfolio.angular
  end

  ########## CREATE PORTFOLIO (new , create) ##########
  def new
    @portfolio_item = Portfolio.new
    # create technologies attr
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your Portfolio is live.' }
      else
        format.html { render :new }
      end
    end
  end

  ########## UPDATE PORTFOLIO (edit, update)##########
  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  ########## SHOW PORTFOLIO ##########
  def show
    @portfolio_item = Portfolio.find(params[:id])
  end


  ########## DELETE PORTFOLIO ##########
  def destroy
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully removed.' }
    end
  end


  ########## PRIVATE METHODS ##########
  private

  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Home Page</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h3>Blogs</h3>
<%= @posts.inspect %>

<h3>Skills</h3>
<%= @skills.inspect %>

app/views/portfolios/edit.html.erb
<h1>Edit portfolio item</h1>

<%= form_for(@portfolio_item) do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :subtitle %>
      <%= f.text_field :subtitle %>
    </div>

    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>
<%= link_to 'Create New Portfolio', new_portfolio_path %>
<% @portfolio_items.each do | portfolio_item | %>
  <p><%= link_to portfolio_item.title  , portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle%></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image if portfolio_item.thumb_image != nil  %>
  <%= link_to 'Edit', edit_portfolio_path(portfolio_item) %>
  <%= link_to 'Delete', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolios/new.html.erb
<h1>Create new portfolio item</h1>

<%= form_for(@portfolio_item) do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :subtitle %>
      <%= f.text_field :subtitle %>
    </div>

    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>

    <ul>
    <!-- This part for nested attributes -->
    <%= f.fields_for :technologies do |tec|  %>
      <li>
        <%= tec.label :name %>
        <%= tec.text_field :name %>
      </li>
       <% end %>
    </ul>
   

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image %>
<h1><%= @portfolio_item.title %></h1>
<h3><%= @portfolio_item.subtitle %></h3>
<p><%= @portfolio_item.body %></p>

<h2>Technologies Used:</h2>
<% @portfolio_item.technologies.each do | t | %>
	<p><%= t.name %></p>
<% end %>
<%= link_to 'All Portfolios', portfolios_path %>